bulletin-board-master/bulletin_board/board/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.PostList.as_view(), name="post_list"),
    path('create/', views.PostCreate.as_view(), name="create_post"),
    path('<int:pk>/', views.PostDetail.as_view(), name="post_detail"),
    path('<int:pk>/update/', views.PostUpdate.as_view(), name="update_post"),
    path('<int:pk>/respond/', views.ResponseCreate.as_view(), name="respond"),
    path('responses/', views.ResponseList.as_view(), name="response_list"),
    path('responses/<int:pk>/', views.ResponseDetail.as_view(), name="response_detail"),
    path('responses/<int:pk>/accept/', views.accept_response, name="accept"),
    path('responses/<int:pk>/deny/', views.deny_response, name="deny"),
    path('success/', views.SuccessView.as_view(), name="success"),
]

bulletin-board-master/bulletin_board/bulletin_board/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('board.urls')),
    path('account/', include('account.urls')),
]

bulletin-board-master/bulletin_board/board/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from ckeditor.fields import RichTextField


class Post(models.Model):
    CATEGORY_CHOICES = [
        ('Tanks', 'Танки'),
        ('Healers', 'Хилы'),
        ('DD', 'ДД'),
        ('Guildmasters', 'Гилдмастеры'),
        ('Questgivers', 'Квестгиверы'),
        ('Smiths', 'Кузнецы'),
        ('Tanners', 'Кожевники'),
        ('Potionbrewers', 'Зельевары'),
        ('Spellmasters', 'Мастера заклинаний')
    ]

    title = models.CharField(max_length=254)
    body = RichTextField()
    category = models.CharField(max_length=254, choices=CATEGORY_CHOICES,)
    created = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.pk)])


class Response(models.Model):
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    status = models.CharField(max_length=1, null=True, choices=[('A', 'Принят'),
                                                                ('D', 'Отклонён')])

bulletin-board-master/bulletin_board/board/forms.py
from django import forms

from .models import Post, Response


class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            'title',
            'body',
            'category',
        ]
        labels = {
            'title': 'Заголовок',
            'body': '',
            'category': 'Категория',
        }


class ResponseCreateForm(forms.ModelForm):
    class Meta:
        model = Response
        fields = [
            'body',
        ]
        labels = {
            'body': ''
        }

bulletin-board-master/bulletin_board/board/views.py
from django.views import generic
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.core.mail import send_mail

from .models import Post, User, Response
from .forms import PostCreateForm, ResponseCreateForm


class PostList(generic.ListView):
    model = Post
    ordering = '-created'
    template_name = 'board/post_list.html'
    context_object_name = 'post_list'


class PostDetail(generic.DetailView):
    model = Post
    template_name = 'board/post_detail.html'


class PostCreate(LoginRequiredMixin, generic.CreateView):
    model = Post
    template_name = 'board/post_edit.html'
    form_class = PostCreateForm

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = User.objects.get(id=self.request.user.id)
        self.object.save()
        result = super().form_valid(form)
        return result


class PostUpdate(LoginRequiredMixin, generic.UpdateView):
    model = Post
    form_class = PostCreateForm

    def get_template_names(self):
        post = self.get_object()
        if post.user == self.request.user:
            self.template_name = 'board/post_edit.html'
            return self.template_name
        else:
            raise PermissionDenied


class ResponseList(LoginRequiredMixin, generic.ListView):
    model = Response
    template_name = 'board/response_list.html'
    context_object_name = 'response_list'
    ordering = '-created'

    def get_queryset(self):
        queryset = Response.objects.filter(post__user=self.request.user)
        return queryset


class ResponseDetail(LoginRequiredMixin, generic.DetailView):
    model = Response

    def get_template_names(self):
        response = self.get_object()
        if response.post.user == self.request.user:
            self.template_name = 'board/response_detail.html'
            return self.template_name
        else:
            raise PermissionDenied


class ResponseCreate(LoginRequiredMixin, generic.CreateView):
    model = Response
    template_name = 'board/response_create.html'
    form_class = ResponseCreateForm
    success_url = '/success/'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = User.objects.get(id=self.request.user.id)
        self.object.post = Post.objects.get(id=self.kwargs['pk'])
        self.object.save()
        result = super().form_valid(form)
        send_mail(
            subject=f'Получен отклик на пост "{self.object.post.title}"',
            message=f'Отклик: "{self.object.body}"',
            from_email='ilya.mikhassik@yandex.ru',
            recipient_list=[self.object.post.user.email]
        )
        return result


class SuccessView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'board/success.html'


@login_required()
def accept_response(request, pk):
    response = Response.objects.get(pk=pk)
    response.status = 'A'
    response.save()
    send_mail(
        subject=f'Доска объявлений: отлик принят',
        message=f'Ваш отклик на пост "{response.post.title}" принят',
        from_email='ilya.mikhassik@yandex.ru',
        recipient_list=[response.user.email]
    )
    return HttpResponseRedirect(reverse('response_list'))


@login_required()
def deny_response(request, pk):
    response = Response.objects.get(pk=pk)
    response.status = 'D'
    response.save()
    return HttpResponseRedirect(reverse('response_list'))

bulletin-board-master/bulletin_board/board/templates/board/post_detail.html
{% extends 'main.html' %}

{% block content %}
{% if user.is_authenticated %}
    <a href="{% url 'logout' %}" style="float:right;"><button>Выйти</button></a>
{% else %}
    <a href="{% url 'login' %}" style="float:right;"><button>Войти</button></a>
{% endif %}
<h1>{{ post.title}}</h1>
{{ post.created|date:'d.m.y' }}
<hr>
{{ post.body|safe }}
<hr>
Отправил: {{ post.user }}<br>
Категория: {{ post.get_category_display }}
<p><a href="{% url 'update_post' pk=post.pk %}"><button>Редактировать</button></a></p>
{% endblock content %}

bulletin-board-master/bulletin_board/board/templates/board/post_edit.html
{% extends 'main.html' %}

{% block title %}
<h1>Создать объявление</h1>
<hr>
{% endblock title %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    {{ form.media }}
    {{ form.as_p }}
    <input type="submit" value="Сохранить"/>
</form>
{% endblock content %}

bulletin-board-master/bulletin_board/board/templates/board/post_list.html
{% extends 'main.html' %}

{% block content %}
{% if user.is_authenticated %}
    <a href="{% url 'logout' %}" style="float:right;"><button>Выйти</button></a>
    <a href="{% url 'create_post' %}"><button> Написать объявление </button></a>
{% else %}
    <a href="{% url 'login' %}" style="float:right;"><button>Войти</button></a>
{% endif %}
{% if post_list %}
    {% for post in post_list %}
        <p><h2>{{ post.title }}</h2></p>
        <hr>
        <p>{{ post.body|safe }}</p>
        <p><a href="{% url 'respond' pk=post.pk %}"><button>Откликнуться</button></a></p>
        <p>Создано пользователем {{ post.user }} в категории "{{ post.get_category_display }}"</p>
        <hr>
    {% endfor %}
{% else %}
    Объявлений нет
{% endif %}
{% endblock content %}

bulletin-board-master/bulletin_board/board/templates/board/response_create.html
{% extends 'main.html' %}

{% block title %}
<h1>Откликнуться на пост</h1>
<hr>
{% endblock title %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Отправить"/>
    <input type="hidden" name="next" value="{{next}}" />
</form>
{% endblock content %}

bulletin-board-master/bulletin_board/board/templates/board/response_detail.html
{% extends 'main.html' %}

{% block content %}
{{ response.created|date:'d.m.y' }}
<hr>
{{ response.body }}
<hr>
Отправил: {{ response.user }}<br>
{% if response.status == 'A' or response.status is None %}
    {% if response.status == 'A' %}
        <p>{{ response.get_status_display }}</p>
    {% else %}
        <a href="{% url 'accept' pk=response.pk %}"><button>Принять</button></a>
        <a href="{% url 'deny' pk=response.pk %}"><button>Отклонить</button></a>
    {% endif %}
{% endif %}
{% endblock content %}

bulletin-board-master/bulletin_board/board/templates/board/response_list.html
{% extends 'main.html' %}

{% block content %}
{% if user.is_authenticated %}
    <a href="{% url 'logout' %}" style="float:right;"><button>Выйти</button></a>
{% else %}
    <a href="{% url 'login' %}" style="float:right;"><button>Войти</button></a>
{% endif %}
{% if response_list %}
    {% for response in response_list %}
        {% if response.status == 'A' or response.status is None %}
            <p>{{ response.created|date:'d.m.y' }}</p>
            <p>{{ response.body }}</p>
            <p>Отклик на "{{ response.post.title }}" от пользователя {{ response.user }}</p>
                {% if response.status == 'A' %}
                    <p>{{ response.get_status_display }}</p>
                {% else %}
                    <a href="{% url 'accept' pk=response.pk %}"><button>Принять</button></a>
                    <a href="{% url 'deny' pk=response.pk %}"><button>Отклонить</button></a>
                {% endif %}
            <hr>
        {% endif %}
    {% endfor %}
{% else %}
    Откликов нет
{% endif %}
{% endblock content %}

bulletin-board-master/bulletin_board/board/templates/board/success.html
{% extends 'main.html' %}

{% block content %}
<h1>Отклик отправлен!</h1>
<a href="{% url 'post_list' %}">К списку постов</a>
{% endblock content %}

bulletin-board-master/bulletin_board/board/templates/board/weekly_post_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for post in post_list %}
        {{ post.title }} <a href="http://{{ domain }}:8000/{{ post.pk }}">Дальше</a><br>
    {% endfor%}
</body>
</html>